### ISSUE TITLE
Space Engineers support

### ISSUE THREAD

**Issue by ekultails** [simons-public/protonfixes#144]
**Is your feature request related to a problem? Please describe.**
Space Engineers support is currently missing from prontofixes.

**Describe the solution you'd like**
These are the steps required to get the game to work:

1. `protontricks 244850 --force -q dotnet472 vcrun2015 faudio d3dcompiler_47`
2. Edit the XML file `$HOME/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/SpaceEngineers.exe.config` and set gcServer to be enabled: `<configuration><runtime><gcServer enabled = "true"/></runtime></configuration>`
3. Rename the intro video file so it does not load (it prevents the game from starting): `$HOME/.local/share/Steam/steamapps/common/SpaceEngineers/Content/Videos/KSH.wmv`

**Describe alternatives you've considered**
As of right now, the [SpaceEngineersLinuxPatches](https://github.com/Linux74656/SpaceEngineersLinuxPatches) project is the only way to apply the fixes in a semi-automated way. It still requires manual steps by using an interactive GUI. This would make more sense to be integrated directly into protonfixes.

**Comment by TheFloatingBrain** [comment]
[I am working on the same thing](https://github.com/ValveSoftware/Proton/issues/1792#issuecomment-925109256)

protontricks hangs on `Executing mkdir -p /home/chris/.steam/steam/steamapps/compatdata/244850` for me though :(

When I try to run a protonfixes script (I was gunna install random .net versions, already tried 4.8 with winetricks)I get 

```
Traceback (most recent call last):
  File "/home/chris/.local/protonfixes/localfixes/244850.py", line 1, in <module>
    from protonfixes import util
  File "/usr/local/lib/python3.9/dist-packages/protonfixes-1.0.15-py3.9.egg/protonfixes/__init__.py", line 12, in <module>
    fix.main()
  File "/usr/local/lib/python3.9/dist-packages/protonfixes-1.0.15-py3.9.egg/protonfixes/fix.py", line 98, in main
    'iscriptevaluator.exe' in sys.argv[2],
IndexError: list index out of range
```

Would love to see this work!!

**Comment by Onyx47** [comment]
Note that installing `dotnet48` seems to alleviate the need for the garbage collector setting.

Also, setting the command line of the game to `%command% -skipintro` removes the need to mess with the video file. Not sure if this is something that can be handled without manual user intervention?
