### ISSUE TITLE
doesn't find wine bin if protondir is in a non-default directory

### ISSUE THREAD

**Issue by Katana-Steel** [simons-public/protonfixes#3]
```
Traceback (most recent call last):
  File "/mnt/data/newdisk/Steam4T/steamapps/common/Proton 3.7/proton", line 142, in <module>
    import user_settings
  File "/mnt/data/newdisk/Steam4T/steamapps/common/Proton 3.7/user_settings.py", line 2, in <module>
    import protonfixes
  File "/home/rene/.local/lib64/python3.4/site-packages/protonfixes/__init__.py", line 9, in <module>
    from . import fix
  File "/home/rene/.local/lib64/python3.4/site-packages/protonfixes/fix.py", line 49, in <module>
    run_fix(game_id())
  File "/home/rene/.local/lib64/python3.4/site-packages/protonfixes/fix.py", line 37, in run_fix
    game_module.main()
  File "/home/rene/.config/protonfixes/localfixes/35140.py", line 13, in main
    util.protontricks('dotnet40')
  File "/home/rene/.local/lib64/python3.4/site-packages/protonfixes/util.py", line 47, in protontricks
    env['WINESERVER'] = os.path.join(protondir(), 'dist/bin/wine')
  File "/home/rene/.local/lib64/python3.4/site-packages/protonfixes/util.py", line 29, in protondir
    'steamapps/common/Proton*'))[0]
IndexError: list index out of range
```

I added this to a local gamefix before the protontricks call:
```
for k,v in os.environ.items():
    if 'STEAM' in k:
        print(k,v)
```
which gave me:
```
Steam Env:
STEAMSCRIPT /usr/bin/steam
SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD 1
STEAMVIDEOTOKEN 000000
XXXXXXX

STEAMSCRIPT_VERSION 100054
STEAM_RUNTIME /home/rene/.local/share/Steam/ubuntu12_32/steam-runtime
STEAM_CLIENT_CONFIG_FILE /home/rene/.local/share/Steam/steam.cfg
STEAM_COMPAT_CLIENT_INSTALL_PATH /home/rene/.local/share/Steam
STEAM_COMPAT_DATA_PATH /mnt/data/newdisk/Steam4T/steamapps/compatdata/35140
STEAM_RUNTIME_LIBRARY_PATH /home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib32/opengl/nvidia/lib:/usr/lib64/opengl/nvidia/lib:/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/32:/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0:/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/32:/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0:/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/32:/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4:/usr/lib32/OpenCL/vendors/nvidia:/usr/lib64/OpenCL/vendors/nvidia:/usr/lib/llvm/5/lib32:/usr/lib/llvm/5/lib64:/usr/lib/llvm/4/lib32:/usr/lib/llvm/4/lib64:/usr/lib32/qt4:/usr/lib64/qt4:/lib64:/usr/lib64:/usr/local/lib64:/lib32:/usr/lib32:/usr/local/lib32:/opt/nvidia-cg-toolkit/lib32:/opt/nvidia-cg-toolkit/lib64:/usr/games/lib64:/usr/local/cuda/lib:/opt/cuda/lib64:/opt/cuda/nvvm/lib64:/usr/lib64/fltk:/usr/lib64/tls:/usr/lib32/tls:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/rene/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib
```

**Comment by simons-public** [comment]
I modified the protondir function to also check using the STEAM_COMPAT_DATA_PATH environment variable. If that doesn't fix it let me know and I'll reopen the issue.
