### ISSUE TITLE
crashing running protonfixes for Soulcalibur6

### ISSUE THREAD

**Issue by farmboy0** [simons-public/protonfixes#85]
**Describe the bug**
ProtonFixes[9295] INFO: Running checks
ProtonFixes[9295] INFO: All checks successful
ProtonFixes[9295] INFO: Using protonfix for "SOULCALIBUR VI" (544750)
ProtonFixes[9295] INFO: Checking if winetricks mf_install is installed
ProtonFixes[9295] INFO: Installing winetricks mf_install
ProtonFixes Traceback (most recent call last):
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/__init__.py", line 19, in <module>
    fix.main()
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/fix.py", line 118, in main
    run_fix(game_id())
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/fix.py", line 79, in run_fix
    game_module.main()
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/gamefixes/544750.py", line 9, in main
    util.protontricks('mf_install')
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/util.py", line 204, in protontricks
    env = dict(protonmain.env)
AttributeError: module '__main__' has no attribute 'env'

**To Reproduce**
Start SC6

**Expected behavior**
media framework gets installed

**Logs**
Please post debug logs to help identify the problem (Preferably on [Gist](https://gist.github.com/)). Steam logs can be found at `/tmp/dumps/$USER_stdout.txt`. Debug info can be enabled by adding `from protonfixes import debug` to your `user_settings.py` file:
```
from protonfixes import debug
import protonfixes
```

**Operating System:**
 - Distro and Version: Gentoo
 - Proton Version: 4.15-GE1

**Game (if applicable):**
 - Game Name: SOULCALIBUR 6
 - Game ID: 544750

**Additional Information**
Add any other information [i.e. Modified Proton, Non-default Steam Library folder, etc] that might be useful in troubleshooting.

**Comment by simons-public** [comment]
The error `AttributeError: module 'main' has no attribute 'env'` looks to be from the new changes in Proton. A pull request from @daniel-j that should fix this has been merged, can you try updating from the Git `master` branch and see if you still have the error?

**Comment by farmboy0** [comment]
With latest master I get:

ProtonFixes Traceback (most recent call last):
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/__init__.py", line 19, in <module>
    fix.main()
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/fix.py", line 118, in main
    run_fix(game_id())
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/fix.py", line 79, in run_fix
    game_module.main()
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/gamefixes/544750.py", line 9, in main
    util.protontricks('mf_install')
  File "/mnt/daten/Home/.local/share/Steam/compatibilitytools.d/Proton-4.15-GE-1/protonfixes/util.py", line 204, in protontricks
    env = dict(protonmain.g_session.env)
AttributeError: module '__main__' has no attribute 'g_session'

**Comment by farmboy0** [comment]
I will close this bug.
This is a problem with Proton 4.15-GE that I used.
@GloriousEggroll  The import protonfixes is still at the wrong place in the proton script
as you added it after sys.exit so it never gets called. It will work if you put it between the session creation and running the proton verb near the comment "#determining mode"
At the moment protonfixes only runs when the user creates a user_settings.py.
